version: "3"
services:
    nginx:
        container_name: nginx-1.25
        image: unixlinuxgeek/nginx:1.25
        restart: always
        ports:
            - "8080:80"  
        volumes:
            - ./src:/src
            - ./nginx/site_advanced.conf:/etc/nginx/conf.d/default.conf
        networks:
          network_1:
            ipv4_address: 172.16.1.2

    php:
        container_name: php-8.3-fpm-alpine
        build: .
        #image: unixlinuxgeek/php:8.3-fpm-alpine
        working_dir: /src
        restart: always
        volumes:
            - ./src/:/src
            - ./php/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - mysql   
        networks:
          network_1:
            ipv4_address: 172.16.1.3
           
    mysql:
        container_name: mysql-8.2
        image: unixlinuxgeek/mysql:8.2
        #command: --default-authentication-plugin=mysql_native_password
        #volumes:
        #    - ./mysql-dumps/megapit_db:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: 12345678
            MYSQL_DATABASE: market_db
            MYSQL_USER: market_db_user
            MYSQL_PASSWORD: 12345678  
        ports:
            - "3306:3306"
        networks:
          network_1:
            ipv4_address: 172.16.1.4

    phpmyadmin:
        image: unixlinuxgeek/phpmyadmin
        container_name: phpmyadmin-1
        environment:
            - UPLOAD_LIMIT=300M
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
        restart: always
        ports:
           - 2000:80
        volumes:
           - /sessions
        networks:
          network_1:
            ipv4_address: 172.16.1.5
        
networks:
  network_1:
    driver: bridge
    ipam:
      config:
        - subnet:  172.16.1.0/24
          #gateway: 172.16.0.1
